### ISSUE TITLE
Issue deploying on openshift

### ISSUE THREAD

**Issue by sean-m-sullivan** [SanderKnape/github-runner#16]
Getting the following error when deploying on openshift, strill trying to track it down. replaced the env variables with their variable names.

```
Requesting token at 'https://api.github.com/repos/GITHUB_OWNER/GITHUB_REPOSITORY/actions/runners/registration-token'
touch: cannot touch '.env': Permission denied
./env.sh: line 36: .path: Permission denied
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/home/github/_diag' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at GitHub.Runner.Common.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
   at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
   at GitHub.Runner.Listener.Program.Main(String[] args)
./config.sh: line 81:    46 Aborted                 (core dumped) ./bin/Runner.Listener configure "$@"
/home/github/entrypoint.sh: 38: /home/github/entrypoint.sh: ./runsvc.sh: Permission denied
```

**Comment by sean-m-sullivan** [comment]
Found answer, is running this command in project to "grants root access to the project you are logged in as" but wonder if there is a better answer
```
oc adm policy add-scc-to-user anyuid -z default
```

**Comment by steveteuber** [comment]
Hi @sean-m-sullivan,

do you have tried to set `runAsUser` in securityContext?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
      ...
```

**Comment by sean-m-sullivan** [comment]
After going down a rabbit hole, involving Security Context, I discovered this was a much deeper and more complex issue and not an issue with your code. I ended up removing the need for sudo, Thanks.
